version: "3.9"
services:
  db:
    image: postgres
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tbl
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"

  # mongo:
  #   image: mongo
  #   restart: unless-stopped
  #   container_name: mongo
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: mongo
  #     MONGO_INITDB_DATABASE: tbl

  persistence:
    image: mill-persistence:0.1.0-SNAPSHOT
    ports:
      - "8081:8081"
    container_name: persistence-container
    links:
      - db
      # - mongo
    volumes:
      - ./persistence:/persistence
    environment:
      FILEIO_SERVICE_HOST: persistence-container
      FILEIO_SERVICE_PORT: 8081
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tbl
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: mongo
      MONGO_DB: tbl

  mill-sa:
    image: mill:0.1.0-SNAPSHOT
    ports:
      - "8080:8080"
    stdin_open: true
    container_name: mill-sa-container
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - .:/sa-mill
    links:
      - persistence
    environment:
      FILEIO_SERVICE_HOST: persistence-container
      FILEIO_SERVICE_PORT: 8081
      DISPLAY: ${DISPLAY:-host.docker.internal:0.0}
    tty: true
