services:
  persistence:
    image: mill-sa-persistence-image
    build:
      context: ./persistence/
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    stdin_open: true
    container_name: persistence-container
    environment:
      FILEIO_SERVICE_HOST: persistence
      FILEIO_SERVICE_PORT: 8081
    tty: true

  mill-sa:
    image: mill-sa-image
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - "persistence"
    ports:
      - "8080:8080"
    stdin_open: true
    container_name: mill-sa-container
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      FILEIO_SERVICE_HOST: persistence
      FILEIO_SERVICE_PORT: 8081
    tty: true
