services:
  db:
    image: postgres
    restart: always
    container_name: database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tbl
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
    ports:
        - "5432:5432"
        
  persistence:
    image: mill-sa-persistence-image
    build:
      context: ./persistence/
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    stdin_open: true
    container_name: persistence-container
    environment:
      FILEIO_SERVICE_HOST: persistence
      FILEIO_SERVICE_PORT: 8081
    tty: true

  mill-sa:
    image: mill-sa-image
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - "persistence"
    ports:
      - "8080:8080"
    stdin_open: true
    container_name: mill-sa-container
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    environment:
      FILEIO_SERVICE_HOST: persistence
      FILEIO_SERVICE_PORT: 8081
      DISPLAY: $DISPLAY
    tty: true
